version: "3.9"
services:
    postgres:
        restart: always
        container_name: postgresSearchMaster
        image: postgres:latest
        environment:
            POSTGRES_DB: "SMDb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5432:5432"

    redis:
        container_name: redisSM
        image: redis
        ports:
            - "6379:6379"

    emailservice:
        container_name: EmailService.API
        image: emailserviceapi
        ports:
            - "8000:8080"
# volumes:
#     posrgres-data:   